TEST_INTERVAL: 1
REGIONS:
  - changsha
DEVICE: cuda
RETRIEVAL_METHODS:
  #  - CAMP
   - MINIMA_Roma_DINOv2
  #  - DINOv3
  #  - DINOv2
MATCHING_METHODS:
  # - Roma
  # - RoMaV2
  - MINIMA_Roma      
  # - MINIMA_LoFTR   
  # - MINIMA_XoFTR
  # - MINIMA_LightGlue

USE_DEM: true

RETRIEVAL_COVER: 60
RETRIEVAL_TOPN: 5
RETRIEVAL_IMG: /1_Retrieval.png
SHOW_RETRIEVAL_IMG_NUM: 5
RETRIEVAL_FEATURE_NORM: true
SHOW_RETRIEVAL_RESULT: true
# SHOW_RETRIEVAL_RESULT: false
BATCH_SIZE: 120

# SPLIT: "train"
SPLIT: "test"
# SPLIT: "valid"

# MODALITY: "Visible"
MODALITY: "Thermal"